# python main_rgb_fused.py recognition -c config/ntu60_xsub/test_rgb_fused.yaml
work_dir: /home/xcl/MMNet-main/workdir/CTR-GCN/test_RGB_fused
weights: /home/xcl/MMNet-main/workdir/3MNet/xsub/RGB_fused/epoch50_model.pt

skeleton_joints_pkl: /home/xcl/3MNet/workdir/3MNet/test_joint/test_result.pkl
skeleton_bones_pkl: /home/xcl/3MNet/workdir/3MNet/test_bone/test_result.pkl

# feeder
feeder: feeder.feeder_rgb_fused_ntu.Feeder
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/val_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl

# model
model: net.mmn.Model
model_args:
  in_channels: 3
  num_class: 60
  graph: graph.ntu_rgb_d.Graph
  # dropout: 0.5
  # edge_importance_weighting: True
  graph_args:
    # layout: 'ntu-rgb+d'
    # strategy: 'spatial'
    labeling_mode: 'spatial'

# test
phase: test
temporal_positions: 15
fix_weights: True
joint_weights: /data/xcl_data/3MNet-master/workdir/3MNet/xsub/joint/epoch75_model.pt
test_batch_size: 32
device: [6, 7, 8, 9]

# debug
debug: False
