# python main_rgb_fused.py recognition -c config/ntu60_xsub/test_rgb_fused.yaml
work_dir: /home/xcl/MMNet-main/workdir/CTR-GCN/test_GOIS
weights: /home/xcl/3MNet/workdir/CTR-GCN/xsub/GOIS/epoch5_model.pt

skeleton_joints_pkl: /home/xcl/3MNet/workdir/3MNet/test_joint/test_result.pkl
skeleton_bones_pkl: /home/xcl/3MNet/workdir/3MNet/test_bone/test_result.pkl

# feeder
feeder: feeder.feeder_GOIS.Feeder
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  temporal_rgb_frames: 1
  data_path: /data/xcl_data/ntu/xsub/val_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl

# model
model: net.mmn.Model
model_args:
  in_channels: 3
  num_class: 60
  #dropout: 0.5
  graph: graph.ntu_rgb_d.Graph
  #edge_importance_weighting: True
  graph_args:
    labeling_mode: 'spatial'
    #layout: 'ntu-rgb+d'
    #strategy: 'spatial'

# test
phase: test
temporal_positions: 1
fix_weights: True
joint_weights: /data/xcl_data/3MNet-master/workdir/3MNet/xsub/joint/epoch75_model.pt
device: [9]
test_batch_size: 64

# debug
debug: False
