# python main_rgb_fused.py recognition -c config/ntu60_xsub/test_rgb_fused.yaml
work_dir: /home/xcl/MMNet-main/workdir/CTR-GCN/test_RGB_fused
weights: models/ntu60/xsub/rgb_fused_model.pt

skeleton_joints_pkl: /home/xcl/3MNet/workdir/CTR-GCN/test_joint/test_result.pkl
skeleton_bones_pkl: /home/xcl/3MNet/workdir/CTR-GCN/test_bone/test_result.pkl

# feeder
feeder: feeder.feeder_rgb_fused_ntu.Feeder
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/val_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl

# model
model: net.mmn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test
phase: test
temporal_positions: 15
fix_weights: True
joint_weights: /home/xcl/3MNet/workdir/CTR-GCN/xsub/joint/runs-65-40690.pt
device: [1,2,3,4,9]

# debug
debug: False
