# python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
work_dir: /home/xcl/3MNet/workdir/CTR-GCN/xsub/GOIS

# skeleton_joints_pkl: /home/xcl/3MNet/workdir/3MNet/test_joint/test_result.pkl
# skeleton_bones_pkl: /home/xcl/3MNet/workdir/3MNet/test_bone/test_result.pkl

# feeder
feeder: feeder.feeder_GOIS.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/train_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/train_label.pkl
  # data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
  # split: train
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  window_size: -1
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/val_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl
  # data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
  # split: test

# model
model: net.cnn.Model
model_args:
  in_channels: 3
  num_class: 60
  num_point: 25
  num_person: 2
  dropout: 0.5
  edge_importance_weighting: True
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    # layout: 'ntu-rgb+d'
    # strategy: 'spatial'
    labeling_mode: 'spatial'
  # examplar: graph.cls_examplar.CLSExamplar
  # examplar_args:
  #   topo_str: "what_will_[J]_act_like_when_[C]-with-punctuation"

# training
# temporal_positions: 15
# fix_weights: True
# joint_weights: /data/xcl_data/3MNet-master/workdir/3MNet/xsub/joint/epoch75_model.pt
device: [7]
weight_decay: 0.0005
base_lr: 0.01
step: [30, 50]
warm_up_epoch: 5
batch_size: 128
test_batch_size: 128
num_epoch: 80

# debug
debug: False
