# python main_rgb.py recognition -c config/ntu60_xsub/train_rgb.yaml
work_dir:  /home/xcl/MMNet-main/workdir/RGB

# feeder
feeder: feeder.feeder_rgb_fused_ntu.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/train_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/train_label.pkl
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/val_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl

# model
model: net.cnn.Model
model_args:
  in_channels: 3
  num_class: 60
  # dropout: 0.5
  graph: graph.ntu_rgb_d.Graph
  edge_importance_weighting: True
  graph_args:
    # layout: 'ntu-rgb+d'
    # strategy: 'spatial'
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [35, 55]

# training
device: [8, 9]
batch_size: 64
test_batch_size: 64
num_epoch: 65
