# python main.py recognition -c config/st_gcn/ntu-xsub/train.yaml
work_dir: /data/xcl_data/HM-CTNet/workdir/HM-CTNet/xsub/bone

# feeder
feeder: feeder.feeder_ntu.Feeder
train_feeder_args:
  data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True
test_feeder_args: 
  data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: net.3MNet.Model
model_args:
  in_channels: 3
  num_class: 60
  num_point: 25
  num_person: 2
  # dropout: 0.5
  # edge_importance_weighting: True
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    # layout: 'ntu-rgb+d'
    # strategy: 'spatial'
    labeling_mode: 'spatial'

#optim
# weight_decay: 0.0001
weight_decay: 0.0001
base_lr: 0.1
# step: [10, 50]
step: [35, 55]
warm_up_epoch: 5 

# training
device: [3, 4]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True

