# python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
work_dir: /home/xcl/3MNet/workdir/CTR-GCN/xsub/RGB_fused

skeleton_joints_pkl: /home/xcl/3MNet/workdir/CTR-GCN/test_joint/test_result.pkl
skeleton_bones_pkl: /home/xcl/3MNet/workdir/CTR-GCN/test_bone/test_result.pkl

# feeder
feeder: feeder.feeder_rgb_fused_ntu.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/train_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/train_label.pkl
  # data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
  # split: train
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  window_size: -1
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/val_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl
  # data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
  # split: test

# model
model: net.mmn.Model
model_args:
  in_channels: 3
  num_class: 60
  num_point: 25
  num_person: 2
  # dropout: 0.5
  # edge_importance_weighting: True
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    # layout: 'ntu-rgb+d'
    # strategy: 'spatial'
    labeling_mode: 'spatial'

# training
temporal_positions: 15
fix_weights: True
joint_weights: /home/xcl/3MNet/workdir/CTR-GCN/xsub/joint/epoch65_model.pt
device: [5, 6]
weight_decay: 0.0001
base_lr: 0.1
step: [35, 55]
# warm_up_epoch: 5
batch_size: 32
test_batch_size: 32
num_epoch: 65

# debug
debug: False



# python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
# work_dir: /home/xcl/3MNet/workdir/ST-GCN/xsub/RGB_fused

# skeleton_joints_pkl: /home/xcl/3MNet/workdir/CTR-GCN/xsub/joint/epoch1_test_score.pkl
# skeleton_bones_pkl: /home/xcl/3MNet/workdir/CTR-GCN/xsub/bone/epoch1_test_score.pkl

# # feeder
# feeder: feeder.feeder_rgb_fused_ntu.Feeder
# train_feeder_args:
#   debug: False
#   random_choose: False
#   centralization: False
#   random_move: False
#   window_size: 64
#   random_flip: False
#   p_interval: [0.5, 1]
#   random_interval: True
#   random_rot: True
#   temporal_rgb_frames: 5
#   data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
#   split: train
#   bone: False
#   # label_path: /data/xcl_data/ntu/xsub/train_label.pkl
# test_feeder_args:
#   debug: False
#   centralization: False
#   evaluation: True
#   window_size: 64
#   temporal_rgb_frames: 5
#   data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
#   split: test
#   bone: False
#   # label_path: /data/xcl_data/ntu/xsub/val_label.pkl

# # model
# model: net.mmn.Model
# model_args:
#   in_channels: 3
#   num_class: 60
#   # dropout: 0.5
#   graph: graph.ntu_rgb_d.Graph
#   # edge_importance_weighting: True
#   graph_args:
#     # layout: 'ntu-rgb+d'
#     # strategy: 'spatial'
#     labeling_mode: 'spatial'

# # training
# temporal_positions: 15
# fix_weights: True
# joint_weights: /home/xcl/3MNet/workdir/CTR-GCN/xsub/joint/runs-65-40690.pt
# device: [2, 3]
# weight_decay: 0.0001
# base_lr: 0.1
# step: [10, 50]
# batch_size: 32
# test_batch_size: 32
# num_epoch: 80

# # debug
# debug: False