# python main_rgb.py recognition -c config/nucla_123/train_rgb.yaml
work_dir: ../../data/st-gcn_nucla/123/with_rgb/rgb_only_

# feeder
feeder: feeder.feeder_rgb_fused_nucla.Feeder
train_feeder_args:
  random_choose: False
  random_move: True
  centralization: False
  window_size: -1
  random_interval: True
  random_roi_move: False
  random_flip: True
  temporal_rgb_frames: 5
  data_path: ../../data/NWestern_UCLA/123/train_data_joint.npy
  label_path: ../../data/NWestern_UCLA/123/train_label.pkl
test_feeder_args:
  centralization: False
  temporal_rgb_frames: 5
  data_path: ../../data/NWestern_UCLA/123/val_data_joint.npy
  label_path: ../../data/NWestern_UCLA/123/val_label.pkl

# model
model: net.cnn.Model
model_args:
  in_channels: 3
  num_class: 10
  edge_importance_weighting: True
  graph_args:
    layout: 'ucla'
    strategy: 'spatial'

# training
device: [0,1]
batch_size: 32
test_batch_size: 32

#optim
base_lr: 0.1
step: [10, 50]
num_epoch: 80
