
# python main_ucla.py recognition -c config/st_gcn/ucla/train_123_skeleton_1.yaml
work_dir: ../../data/st-gcn/ucla/skeleton/123_
#weights: ../../data/st-gcn/ucla/skeleton/123_3/epoch30_model.pt
weights: ../../data/st-gcn/ucla/skeleton/123/best_model.pt

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: False
  random_move: True
  window_size: -1
  centralization: False
  data_path: ../../data/NWestern_UCLA/123/train_data_joint.npy
  label_path: ../../data/NWestern_UCLA/123/train_label.pkl
test_feeder_args:
  centralization: False
  data_path: ../../data/NWestern_UCLA/123/val_data_joint.npy
  label_path: ../../data/NWestern_UCLA/123/val_label.pkl

# model
#model: net.st_gcn_BK.Model
model: net.st_gcn_BK.Model
model_args:
  in_channels: 3
  num_class: 10
  #dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ucla'
    strategy: 'spatial'

# training
device: [0,1]
batch_size: 64
test_batch_size: 64

#optim
base_lr: 0.1
step: [10, 50]
num_epoch: 80
