# python main_rgb.py recognition -c config/st_gcn/ntu-xview/train_rgb_test.yaml
#weights: ../../data/st-gcn/with-rgb/full_rgb_only/xview_reg/epoch80_model.pt
work_dir: ../../data/st-gcn/with-rgb/full_rgb_only/xview_reg
weights: ../../data/st-gcn/with-rgb/full_rgb_only/xview_reg/epoch65_model.pt

# feeder
feeder: feeder.feeder.Feeder

test_feeder_args:
  data_path: /media/bruce/2Tssd/data/ntu-rgbd-st-gcn/xview/val_data.npy
  label_path: /media/bruce/2Tssd/data/ntu-rgbd-st-gcn/xview/val_label.pkl

# model
model: net.cnn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.2
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# training
phase: test
device: [0,1,2,3]
test_batch_size: 64
# save
save_result: True
