# python main_rgb_fused.py recognition -c config/nucla_132/train_rgb_fused.yaml
work_dir: ../../data/st-gcn/ucla/sklweight_auto/rgb_tp15_tf5_

skeleton_joints_pkl: results/nucla/132/joint_result_msg3d.pkl
skeleton_bones_pkl: results/nucla/132/bone_result_msg3d.pkl

# feeder
feeder: feeder.feeder_rgb_fused_nucla.Feeder
train_feeder_args:
  random_choose: False
  random_move: True
  centralization: False
  window_size: -1
  random_interval: True
  random_roi_move: False
  random_flip: True
  temporal_rgb_frames: 5
  data_path: ../../data/NWestern_UCLA/132/train_data_joint.npy
  label_path: ../../data/NWestern_UCLA/132/train_label.pkl
test_feeder_args:
  centralization: False
  temporal_rgb_frames: 5
  data_path: ../../data/NWestern_UCLA/132/val_data_joint.npy
  label_path: ../../data/NWestern_UCLA/132/val_label.pkl

# model
model: net.mmn_nucla.Model
model_args:
  in_channels: 3
  num_class: 10
  edge_importance_weighting: True
  graph_args:
    layout: 'ucla'
    strategy: 'spatial'

# training
temporal_positions: 15
fix_weights: False
joint_weights: models/nucla/132/joint_model_stgcn.pt
device: [0,1,2,3]
base_lr: 0.1
step: [10, 50]
num_epoch: 80
batch_size: 64
test_batch_size: 64
