# python main.py recognition -c config/st_gcn/ntu-xsub/test.yaml

work_dir: ../../data/st-gcn/skl/2s_lr01
weights: models/ntu120/xsub/bone_model_stgcn.pt

# feeder
feeder: feeder.feeder_skeleton.Feeder
test_feeder_args:
  centralization: False
  if_bone: False
  data_path: data/ntu120/xsub/val_data.npy
  label_path: data/ntu120/xsub/val_label.pkl

# model
model: net.gcn.Model
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test
phase: test
device: [0,1,2,3]
test_batch_size: 64

# save
save_result: True
