# python main_rgb.py recognition -c config/st_gcn/ntu-xset/train_rgb.yaml
work_dir: ../../data/st-gcn-ntu120/xset/with-rgb/rgb_only_rz18

feeder: feeder.feeder_rgb_fused_ntu.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: False
  data_path: /media/bruce/2Tssd/data/ntu120/xset/train_data_joint.npy
  label_path: /media/bruce/2Tssd/data/ntu120/xset/train_label.pkl
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  data_path: /media/bruce/2Tssd/data/ntu120/xset/val_data_joint.npy
  label_path: /media/bruce/2Tssd/data/ntu120/xset/val_label.pkl

# model
model: net.cnn.Model
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]
#eval_interval: 1

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 64
num_epoch: 80
