# python main.py recognition -c config/st_gcn/ntu-xsub/test.yaml

work_dir: /home/xcl/MMNet-main/workdir/ST-GCN/xsub/test_bone
weights: /home/xcl/MMNet-main/workdir/ST-GCN/xsub/bone/epoch60_model.pt

# feeder
feeder: feeder.feeder_skeleton.Feeder
test_feeder_args:
  centralization: False
  if_bone: False
  data_path: /data/xcl_data/ntu/xsub/val_data_bone.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl

# model
model: net.gcn.Model
model_args:
  in_channels: 3
  num_point: 25
  num_class: 60
  # dropout: 0.5
  # edge_importance_weighting: True
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    # layout: 'ntu-rgb+d'
    # strategy: 'spatial'
    labeling_mode: 'spatial'

# test
phase: test
device: [7, 8, 9]
test_batch_size: 64

# save
save_result: True
