# python main_rgb_fused.py recognition -c config/ntu60_xsub/train_rgb_fused.yaml
work_dir: /home/xcl/MMNet-main/workdir/ST-GCN/xsub/RGB_fused

skeleton_joints_pkl: /data/xcl_data/CTR-GCN-main/work_dir/ntu60/xsub/ctrgcn_joint/epoch1_test_score.pkl
skeleton_bones_pkl: /data/xcl_data/CTR-GCN-main/work_dir/ntu60/xsub/ctrgcn_bone/epoch1_test_score.pkl

# feeder
feeder: feeder.feeder_rgb_fused_ntu.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/CTR-GCN-main/data/ntu/NTU60_CS.npz
  # label_path: /data/xcl_data/ntu/xsub/train_label.pkl
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  temporal_rgb_frames: 5
  data_path: /data/xcl_data/ntu/xsub/val_data_joint.npy
  label_path: /data/xcl_data/ntu/xsub/val_label.pkl

# model
model: net.mmn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# training
temporal_positions: 15
fix_weights: True
joint_weights: /data/xcl_data/CTR-GCN-main/work_dir/ntu60/xsub/ctrgcn_joint/runs-65-40690.pt
device: [1, 2, 3, 4]
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]
batch_size: 32
test_batch_size: 32
num_epoch: 80

# debug
debug: False
