# python main.py recognition -c config/st_gcn/ntu-xsub/train.yaml
work_dir: ../../data/st-gcn-ntu120/xsub/skl_joint_rm

# feeder
feeder: feeder.feeder_skeleton.Feeder
train_feeder_args:
  centralization: False
  random_move: True
  if_bone: False
  data_path: /media/bruce/2Tssd/data/ntu120/xsub/train_data_joint.npy
  label_path: /media/bruce/2Tssd/data/ntu120/xsub/train_label.pkl
test_feeder_args:
  centralization: False
  if_bone: False
  data_path: /media/bruce/2Tssd/data/ntu120/xsub/val_data_joint.npy
  label_path: /media/bruce/2Tssd/data/ntu120/xsub/val_label.pkl

# model
model: net.gcn.Model
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 64
num_epoch: 50
